### ISSUE TITLE
Add python dependency list in documentation

### ISSUE THREAD

**Issue by HielkeVeringa** [PalmSens/emstatpico#5]

**Comment by wouter-palmsens** [comment]
This has been implemened in the new [MethodSCRIPT_Examples](https://github.com/PalmSens/MethodSCRIPT_Examples) repository. The documentation now contains some installation instructions. See also the [requirements.txt](https://github.com/PalmSens/MethodSCRIPT_Examples/blob/master/MethodSCRIPTExample_Python/MethodSCRIPTExample_Python/requirements.txt).
